/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kurswork.info;

import kurswork.MainClass;

public class BMRM extends javax.swing.JFrame {

    String view = new MainClass().view;
    double height = new MainClass().height;
    double weight = new MainClass().weight;
    double age = new MainClass().age;
int x1 = 655;
double x2 = 9.6;
double x3 = 1.8;
double x4 = 4.7;

    public BMRM() {
        super("BMR калкулятор");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        heightTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        weightTF = new javax.swing.JTextField();
        resultL = new javax.swing.JLabel();
        resultB = new javax.swing.JButton();
        nameL1 = new javax.swing.JLabel();
        femaleB = new javax.swing.JButton();
        maleB = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ageTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        maxL = new javax.swing.JLabel();
        strongL = new javax.swing.JLabel();
        mediumL = new javax.swing.JLabel();
        minL = new javax.swing.JLabel();
        sidL = new javax.swing.JLabel();
        womanP = new javax.swing.JPanel();
        manP = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        nameL2 = new javax.swing.JLabel();
        nameL3 = new javax.swing.JLabel();
        nameL4 = new javax.swing.JLabel();
        nameL5 = new javax.swing.JLabel();
        nameL6 = new javax.swing.JLabel();
        nameL7 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(253, 193, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 144, 62));

        jLabel1.setBackground(new java.awt.Color(36, 29, 112));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 235, 235));
        jLabel1.setText("MARATHON SKILLS 2017");

        jButton1.setBackground(new java.awt.Color(253, 193, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(80, 80, 80));
        jButton1.setText("Назад");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 799, -1));

        jPanel4.setBackground(new java.awt.Color(0, 144, 62));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 235, 235));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(scripts.Timer.rasnica());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 554, 799, -1));

        nameL.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        nameL.setForeground(new java.awt.Color(80, 80, 80));
        nameL.setText("калорий:");
        jPanel2.add(nameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 70, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 80));
        jLabel5.setText("Рост:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(80, 80, 80));
        jLabel6.setText("Вес:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        heightTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTFActionPerformed(evt);
            }
        });
        jPanel2.add(heightTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 54, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(80, 80, 80));
        jLabel7.setText("см");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(80, 80, 80));
        jLabel8.setText("кг");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        weightTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTFActionPerformed(evt);
            }
        });
        jPanel2.add(weightTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 54, -1));

        resultL.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        resultL.setForeground(new java.awt.Color(80, 80, 80));
        jPanel2.add(resultL, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 120, 40));

        resultB.setBackground(new java.awt.Color(0, 144, 62));
        resultB.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        resultB.setForeground(new java.awt.Color(80, 80, 80));
        resultB.setText("Рассчитать");
        resultB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultBActionPerformed(evt);
            }
        });
        jPanel2.add(resultB, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 489, -1, -1));

        nameL1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        nameL1.setForeground(new java.awt.Color(80, 80, 80));
        nameL1.setText("возраста и различных медицинских факторов.");
        jPanel2.add(nameL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        femaleB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/materials/icon/female-icon.png"))); // NOI18N
        femaleB.setText("Женский");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, buttonGroup1, org.jdesktop.beansbinding.ELProperty.create("${selection.selected}"), femaleB, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        femaleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleBActionPerformed(evt);
            }
        });
        jPanel2.add(femaleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 199, -1, -1));

        maleB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/materials/icon/male-icon.png"))); // NOI18N
        maleB.setText("Мужской");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, buttonGroup1, org.jdesktop.beansbinding.ELProperty.create("${selection.selected}"), maleB, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        maleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleBActionPerformed(evt);
            }
        });
        jPanel2.add(maleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 199, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(80, 80, 80));
        jLabel9.setText("Возраст:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        ageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTFActionPerformed(evt);
            }
        });
        jPanel2.add(ageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 54, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(80, 80, 80));
        jLabel10.setText("лет");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(36, 29, 112));
        jLabel11.setText("Сидячий:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Максимальная активность:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 490, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("Средняя активность:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 412, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 144, 62));
        jLabel14.setText("Маленькая активность:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 376, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("Сильная активность:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 448, -1, -1));

        maxL.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        maxL.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(maxL, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 60, 40));

        strongL.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        strongL.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(strongL, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 60, 40));

        mediumL.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        mediumL.setForeground(new java.awt.Color(255, 102, 0));
        jPanel2.add(mediumL, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 60, 40));

        minL.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        minL.setForeground(new java.awt.Color(0, 144, 62));
        jPanel2.add(minL, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 60, 40));

        sidL.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        sidL.setForeground(new java.awt.Color(36, 29, 112));
        jPanel2.add(sidL, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 60, 40));

        womanP.setBackground(new java.awt.Color(36, 29, 112));

        javax.swing.GroupLayout womanPLayout = new javax.swing.GroupLayout(womanP);
        womanP.setLayout(womanPLayout);
        womanPLayout.setHorizontalGroup(
            womanPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        womanPLayout.setVerticalGroup(
            womanPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel2.add(womanP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 150, 140));
        womanP.setVisible(false);

        manP.setBackground(new java.awt.Color(36, 29, 112));
        manP.setPreferredSize(new java.awt.Dimension(140, 140));

        javax.swing.GroupLayout manPLayout = new javax.swing.GroupLayout(manP);
        manP.setLayout(manPLayout);
        manPLayout.setHorizontalGroup(
            manPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        manPLayout.setVerticalGroup(
            manPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel2.add(manP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, 140));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/materials/icon/вопрос.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 40, 40));

        nameL2.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        nameL2.setForeground(new java.awt.Color(80, 80, 80));
        nameL2.setText("BMR используется в качестве оценки");
        jPanel2.add(nameL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        nameL3.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        nameL3.setForeground(new java.awt.Color(80, 80, 80));
        nameL3.setText("для измерения метаболизма взрослого человека,");
        jPanel2.add(nameL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        nameL4.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        nameL4.setForeground(new java.awt.Color(80, 80, 80));
        nameL4.setText("который изменяется в зависимости от роста, веса, ");
        jPanel2.add(nameL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        nameL5.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        nameL5.setForeground(new java.awt.Color(80, 80, 80));
        nameL5.setText("BMR КАЛЬКУЛЯТОР");
        jPanel2.add(nameL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        nameL6.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        nameL6.setForeground(new java.awt.Color(80, 80, 80));
        nameL6.setText("Ваш BMR");
        jPanel2.add(nameL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        nameL7.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        nameL7.setForeground(new java.awt.Color(80, 80, 80));
        nameL7.setText("Ежедневно тратится");
        jPanel2.add(nameL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleBActionPerformed
x1 = 66;
x2 = 13.7;
x3 = 5;
x4 = 6.8;
manP.setVisible(true);
womanP.setVisible(false);
    }//GEN-LAST:event_maleBActionPerformed

    private void heightTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTFActionPerformed
  view =heightTF.getText();
  height = Integer.parseInt(view);
  view = null;
  // TODO add your handling code here:
    }//GEN-LAST:event_heightTFActionPerformed

    private void weightTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTFActionPerformed
view =weightTF.getText();
  weight = Integer.parseInt(view);
  view = null;
    }//GEN-LAST:event_weightTFActionPerformed

    private void resultBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultBActionPerformed
  view =heightTF.getText();
  height = Integer.parseInt(view);
  view = null;
  view =weightTF.getText();
  weight = Integer.parseInt(view);
  view = null;
  view =ageTF.getText();
  age = Integer.parseInt(view);
  view = null;  
        double bmr = (x1 + (x2 * weight) + (x3 * height) - (x4 * age))/1000;
resultL.setText(String.format("%(.3f", bmr));// TODO add your handling code here:
 view = null;
double  bmrres = bmr * 1.2;
sidL.setText(String.format("%(.3f", bmrres));
bmrres = bmr * 1.375;
minL.setText(String.format("%(.3f", bmrres));
bmrres = bmr * 1.55;
mediumL.setText(String.format("%(.3f", bmrres));
bmrres = bmr * 1.725;
strongL.setText(String.format("%(.3f", bmrres));
bmrres = bmr * 1.9;
maxL.setText(String.format("%(.3f", bmrres));
    }//GEN-LAST:event_resultBActionPerformed

    private void femaleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleBActionPerformed
x1 = 655;
x2 = 9.6;
x3 = 1.8;
x4 = 4.7;
womanP.setVisible(true);
manP.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_femaleBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new kurswork.info.InfoMenu().setVisible(true);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTFActionPerformed
view =ageTF.getText();
  age = Integer.parseInt(view);
  view = null;        // TODO add your handling code here:
    }//GEN-LAST:event_ageTFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new BMRMinfo().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTF;
    private javax.swing.ButtonGroup buttonGroup1;
    javax.swing.JButton femaleB;
    private javax.swing.JTextField heightTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton maleB;
    private javax.swing.JPanel manP;
    private javax.swing.JLabel maxL;
    private javax.swing.JLabel mediumL;
    private javax.swing.JLabel minL;
    private javax.swing.JLabel nameL;
    private javax.swing.JLabel nameL1;
    private javax.swing.JLabel nameL2;
    private javax.swing.JLabel nameL3;
    private javax.swing.JLabel nameL4;
    private javax.swing.JLabel nameL5;
    private javax.swing.JLabel nameL6;
    private javax.swing.JLabel nameL7;
    private javax.swing.JButton resultB;
    private javax.swing.JLabel resultL;
    private javax.swing.JLabel sidL;
    private javax.swing.JLabel strongL;
    private javax.swing.JTextField weightTF;
    private javax.swing.JPanel womanP;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
