/*
Контакты для связи с руководством (Жека)
 */
package kurswork.runner;

/**
 *
 * @author user
 */
public class Contacts extends javax.swing.JFrame {

    /**
     * Создана из формы шаблона(Альберт) 
     */
    public Contacts() {
        super("Контакты");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        mainP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 320));
        setMinimumSize(new java.awt.Dimension(480, 320));
        setPreferredSize(new java.awt.Dimension(480, 320));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainP.setBackground(new java.awt.Color(253, 193, 0));
        mainP.setMaximumSize(new java.awt.Dimension(480, 320));
        mainP.setMinimumSize(new java.awt.Dimension(480, 320));
        mainP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 80));
        jLabel1.setText("Контакты");
        mainP.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 63, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 29, 112));
        jLabel2.setText("Для получания дополнительной информации ");
        mainP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 105, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 29, 112));
        jLabel3.setText("Телефон:");
        mainP.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 179, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 29, 112));
        jLabel7.setText("пожалуйста, свяжитесь с координаторами");
        mainP.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 142, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 29, 112));
        jLabel9.setText("+55 11 9988 7766");
        mainP.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 179, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(36, 29, 112));
        jLabel15.setText("eMail:");
        mainP.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 209, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(36, 29, 112));
        jLabel16.setText("Coordinators@marathonskills.org");
        mainP.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 209, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/materials/icon/cross-icon - копия.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainP.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 45, 45));

        getContentPane().add(mainP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contacts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainP;
    // End of variables declaration//GEN-END:variables
}
