
package kurswork.runner;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import kurswork.HomeF;
import kurswork.MainClass;


public class MenuRunner extends javax.swing.JFrame {

 
    public MenuRunner() {
        super("Меню бегуна");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainP = new javax.swing.JPanel();
        headP = new javax.swing.JPanel();
        backB = new javax.swing.JButton();
        titleL = new javax.swing.JLabel();
        logoutB = new javax.swing.JButton();
        dawnP = new javax.swing.JPanel();
        timeL = new javax.swing.JLabel();
        nameL = new javax.swing.JLabel();
        siginOfMarathonB = new javax.swing.JButton();
        resultB = new javax.swing.JButton();
        editB = new javax.swing.JButton();
        sponsorB = new javax.swing.JButton();
        contactB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainP.setBackground(new java.awt.Color(253, 193, 0));
        mainP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headP.setBackground(new java.awt.Color(0, 144, 62));

        backB.setBackground(new java.awt.Color(253, 193, 0));
        backB.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        backB.setForeground(new java.awt.Color(80, 80, 80));
        backB.setText("Назад");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });

        titleL.setBackground(new java.awt.Color(36, 29, 112));
        titleL.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        titleL.setForeground(new java.awt.Color(235, 235, 235));
        titleL.setText("MARATHON SKILLS 2017");

        logoutB.setBackground(new java.awt.Color(253, 193, 0));
        logoutB.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        logoutB.setForeground(new java.awt.Color(80, 80, 80));
        logoutB.setText("Выйти");
        logoutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headPLayout = new javax.swing.GroupLayout(headP);
        headP.setLayout(headPLayout);
        headPLayout.setHorizontalGroup(
            headPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(backB)
                .addGap(119, 119, 119)
                .addComponent(titleL, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(logoutB)
                .addGap(52, 52, 52))
        );
        headPLayout.setVerticalGroup(
            headPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headPLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(headPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleL)
                    .addComponent(backB)
                    .addComponent(logoutB))
                .addGap(20, 20, 20))
        );

        mainP.add(headP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dawnP.setBackground(new java.awt.Color(0, 144, 62));

        timeL.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        timeL.setForeground(new java.awt.Color(235, 235, 235));
        timeL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeL.setText(scripts.Timer.rasnica());

        javax.swing.GroupLayout dawnPLayout = new javax.swing.GroupLayout(dawnP);
        dawnP.setLayout(dawnPLayout);
        dawnPLayout.setHorizontalGroup(
            dawnPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dawnPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeL, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );
        dawnPLayout.setVerticalGroup(
            dawnPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dawnPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timeL, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainP.add(dawnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 800, -1));

        nameL.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        nameL.setForeground(new java.awt.Color(80, 80, 80));
        nameL.setText("Меню бегуна");
        mainP.add(nameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 81, -1, -1));

        //"<html><p align-center>Благотворительные</p>организации</html>"
        siginOfMarathonB.setBackground(new java.awt.Color(0, 144, 62));
        siginOfMarathonB.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        siginOfMarathonB.setForeground(new java.awt.Color(80, 80, 80));
        siginOfMarathonB.setText("<html><p>Регистрация на</p>марафон</html>");
        siginOfMarathonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siginOfMarathonBActionPerformed(evt);
            }
        });
        mainP.add(siginOfMarathonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 157, 190, 50));

        resultB.setBackground(new java.awt.Color(0, 144, 62));
        resultB.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        resultB.setForeground(new java.awt.Color(80, 80, 80));
        resultB.setText("Мои результаты");
        mainP.add(resultB, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 157, 198, 50));

        editB.setBackground(new java.awt.Color(0, 144, 62));
        editB.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        editB.setForeground(new java.awt.Color(80, 80, 80));
        editB.setText("<html><p>Редактирование</p>профиля</html>");
        editB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBActionPerformed(evt);
            }
        });
        mainP.add(editB, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 273, 190, 50));

        sponsorB.setBackground(new java.awt.Color(0, 144, 62));
        sponsorB.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        sponsorB.setForeground(new java.awt.Color(80, 80, 80));
        sponsorB.setText("Мой спонсор");
        sponsorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sponsorBActionPerformed(evt);
            }
        });
        mainP.add(sponsorB, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 273, 190, 50));

        contactB.setBackground(new java.awt.Color(0, 144, 62));
        contactB.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        contactB.setForeground(new java.awt.Color(80, 80, 80));
        contactB.setText("Контакты");
        contactB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactBActionPerformed(evt);
            }
        });
        mainP.add(contactB, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 392, 190, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        new HomeF().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBActionPerformed

    private void logoutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBActionPerformed
        new HomeF().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBActionPerformed

    private void contactBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactBActionPerformed
    new Contacts().setVisible(true);       
    }//GEN-LAST:event_contactBActionPerformed

    private void siginOfMarathonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siginOfMarathonBActionPerformed
    new RegOnMar().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_siginOfMarathonBActionPerformed

    private void editBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBActionPerformed
    new EditRunner().setVisible(true);
    this.dispose();        
    }//GEN-LAST:event_editBActionPerformed

    private void sponsorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sponsorBActionPerformed
        try {
            new SponsorRun().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MenuRunner.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_sponsorBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRunner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB;
    private javax.swing.JButton contactB;
    private javax.swing.JPanel dawnP;
    private javax.swing.JButton editB;
    private javax.swing.JPanel headP;
    private javax.swing.JButton logoutB;
    private javax.swing.JPanel mainP;
    private javax.swing.JLabel nameL;
    private javax.swing.JButton resultB;
    private javax.swing.JButton siginOfMarathonB;
    private javax.swing.JButton sponsorB;
    private javax.swing.JLabel timeL;
    private javax.swing.JLabel titleL;
    // End of variables declaration//GEN-END:variables
}
