/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kurswork.runner;
import java.io.IOException;
import kurswork.runner.RegOnMar;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.lang.*;
import kurswork.MainClass;



/**
 *
 * @author user
 */
public class SponsorInfo extends javax.swing.JFrame {
  String charName;
  String charDes;
  String charLog;
        /**
     * Creates new form Wablon
     */
    public SponsorInfo() throws IOException, SQLException {
super("Информация о благотворительной организации");
          Connection con = DriverManager.getConnection(MainClass.URL, MainClass.USER, MainClass.PASS);
           
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("select CharityName, CharityDescription, CharityLogo from charity where CharityId = '" + RegOnMar.charityNum + "';");
                rs.next();
                 charName = rs.getString("CharityName");
                 charDes = rs.getString("CharityDescription");
                 charLog = rs.getString("CharityLogo");
                rs.close();
                stmt.close();
            con.close();
        
                        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        mainP = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        iconLog = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoTA = new javax.swing.JTextArea();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainP.setBackground(new java.awt.Color(253, 193, 0));
        mainP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/materials/icon/cross-icon - копия.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainP.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 11, 45, 45));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(80, 80, 80));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(charName);
        mainP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 392, 55));

        iconLog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/materials/charityLogo/" + charLog + "")));
        mainP.add(iconLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 190, 130));

        infoTA.setEditable(false);
        infoTA.setBackground(new java.awt.Color(253, 193, 0));
        infoTA.setColumns(20);
        infoTA.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        infoTA.setLineWrap(true);
        infoTA.setRows(5);
        infoTA.append(charDes);
        jScrollPane2.setViewportView(infoTA);

        mainP.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 560, 180));

        getContentPane().add(mainP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SponsorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SponsorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SponsorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SponsorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SponsorInfo().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(SponsorInfo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(SponsorInfo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLog;
    private javax.swing.JTextArea infoTA;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainP;
    // End of variables declaration//GEN-END:variables
}
