
package kurswork.runner;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import kurswork.MainClass;



/**
 *
 * @author user
 */
public class SponsorInfo extends javax.swing.JFrame {
  String charName;
  String charDes;
  String charLog;

    public SponsorInfo() {
        super("Информация о благотворительной организации");
        System.out.println(RegOnMar.charityNum);          
              
        initComponents();
        {getData(); }
        setLocationRelativeTo(null);
    }

    
    private void getData()
    {
        System.out.println(RegOnMar.charityNum);
          Connection con;
      try {
          con = DriverManager.getConnection(MainClass.URL, MainClass.USER, MainClass.PASS);    
          Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("select * from charity where CharityName like '%" + RegOnMar.charityNum + "%';");
                while(rs.next()){
                 charName = rs.getString(2);
                 charDes = rs.getString(3);
                 charLog = rs.getString(4);
                    System.out.println(charName);
                    //System.out.println(charDes);
                    System.out.println(charLog);
                     infoTA.append(charDes);
                     ImageIcon icon = new ImageIcon("/materials/charityLogo/arise-logo.png");
                    iconLogL.setIcon(icon);
                     jLabel2.setText(charName);
                }
               
                
               // try{
                    
                //}catch(Exception ex){System.out.print("Картинка");System.err.println(ex);;}
                rs.close();
                stmt.close();
            con.close();
          
      } catch (SQLException ex) {
          Logger.getLogger(SponsorInfo.class.getName()).log(Level.SEVERE, null, ex);
          System.err.print(ex);
          System.out.println("?");
          JOptionPane.showMessageDialog(this, "тут?", "", JOptionPane.ERROR_MESSAGE);
      }         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainP = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoTA = new javax.swing.JTextArea();
        iconLogL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainP.setBackground(new java.awt.Color(253, 193, 0));
        mainP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainP.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 45, 45));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(80, 80, 80));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 392, 55));

        infoTA.setEditable(false);
        infoTA.setBackground(new java.awt.Color(253, 193, 0));
        infoTA.setColumns(20);
        infoTA.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        infoTA.setLineWrap(true);
        infoTA.setRows(5);
        jScrollPane2.setViewportView(infoTA);

        mainP.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 560, 180));
        mainP.add(iconLogL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 26, 400, 170));

        getContentPane().add(mainP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SponsorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SponsorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SponsorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SponsorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                    new SponsorInfo().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLogL;
    private javax.swing.JTextArea infoTA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainP;
    // End of variables declaration//GEN-END:variables
}
